// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlnddfcbojysyryjijlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsbmRkZmNib2p5c3lyeWppamxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODk5NDAsImV4cCI6MjA2NTQ2NTk0MH0.IXQfdfgi-jivgu5OetgrXhHC8l83YzqBFDWwdHVJl7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);